### ISSUE TITLE
试用过程中的一些问题。

### ISSUE THREAD

**Issue by qingwuit** [drinkjs/mojito#1]
首先十分感谢作者开源的框架，让我可以由编程面向clone。

下面是我使用过程遇到的一些问题

1、**尽量使用 yarn安装扩展**，不然会各种运行报错，我一开始使用npm安装反正怀疑人生，后来以为是网络问题，删了module好几次又使用淘宝的cnpm去搞还是不行，最后使用yarn重新捣鼓了一遍，**虽然Server服务端报错**，得yarn启动，npm暂时不行，但是至少能正常运行了，身为一个php太为难我了

2、`在平台使用时，所有图层都会透传一个styles, styles, styles属性给组件，styles包含的当前图层长宽位置等信息` 这个styles属性建议列在文档，fontSize，height，overflow，width，x,y,z,当然不列也没关系，

3、有没有交流社群，太难了。。。

功能实在是太强大了，就是看不懂nodejs代码，先研究下看能不能把后端改造下成php的。

**Comment by razr001** [comment]
感谢你的使用和反馈，平台的核心功能最近才完成，所以文档相对滞后，近期我会把文档完善。
社群这个暂时没有考虑，如果遇到问题欢迎提issue，我会尽快回复
后端的功能其实并不复杂，主要是储存数据和一些简单的验证
