### ISSUE TITLE
还有一个问题就是在项目上运行自己写的echarts，不能实现鼠标放上去出现悬浮的效果

### ISSUE THREAD

**Issue by xiahongyuan** [drinkjs/mojito#10]

**Comment by xiahongyuan** [comment]
![image](https://user-images.githubusercontent.com/88996467/167062918-36bf41f2-3d2b-422d-925a-1dee0db22952.png)

**Comment by razr001** [comment]
看下是不是打开了事件锁定，工具栏上的第一个开关
