### ISSUE TITLE
发现一点问题想请教下

### ISSUE THREAD

**Issue by qingwuit** [drinkjs/mojito#2]
组件在拖到 画板上的时候可以正常显示，但是当我预览的时候却显示

**Vue未定义，请检查CDN配置**

我看了下，获取element按钮组件的时候后台接口是有dependencies 这个字段，然后拖到画板上，跑**update/layer**接口后，dependencies 这个字段内的东西消失了，反而导致 screen保存的时候dependencies 为空了

所以预览的时候报出**Vue未定义，请检查CDN配置**，我去看线上的示例好像也是这样子，拖进去组件后跑**update/layer**接口**dependencies为空** ，

**请问是哪个文件的问题了**，找了半天没找到，如果有时间希望作者看看是我本地的问题，还是开源代码有bug
谢谢。

**Comment by razr001** [comment]
恩，新增时dependencies变空是因为加载CDN时被shift掉了，我已经修改了这部分代码，并优化了更新图层的数据。但实际上后端在更新图层时只用到compoent.id，在预览时会通过component.id查出组件的明细和图层数据一并返回，所以这个问题跟update/layer接口dependencies为空应该没有直接关系，不过你更新代码试试看，如果还是不行，需要你提供下面的信息

1. 你的element按钮是自己封装的吗，是否可提供源码
2. vue的cdn地址是否可正常访问
3. 你是使用本地环境，还是demo环境

**Comment by qingwuit** [comment]
谢谢，已经明白了错误的地方。
我本地搭建的环境，按钮应该是没问题。
应该是我后端代码做了改动的原因，我想减少数据库查询，想着前端能直接传过去，然后历史组件不至于报错
再后端改造过程中就把图层获取数据的接口，**this.componentService.findByIds(componentIds);**这一段给删掉了，
导致CDN数据直接获取的screen里面的，
应该是我代码的问题，谢谢了。

**Comment by qingwuit** [comment]
> 恩，新增时dependencies变空是因为加载CDN时被shift掉了，我已经修改了这部分代码，并优化了更新图层的数据。但实际上后端在更新图层时只用到compoent.id，在预览时会通过component.id查出组件的明细和图层数据一并返回，所以这个问题跟update/layer接口dependencies为空应该没有直接关系，不过你更新代码试试看，如果还是不行，需要你提供下面的信息
> 
> 1. 你的element按钮是自己封装的吗，是否可提供源码
> 2. vue的cdn地址是否可正常访问
> 3. 你是使用本地环境，还是demo环境

谢谢，已经明白了错误的地方。
我本地搭建的环境，按钮应该是没问题。
应该是我后端代码做了改动的原因，我想减少数据库查询，想着前端能直接传过去，然后历史组件不至于报错
再后端改造过程中就把图层获取数据的接口，**this.componentService.findByIds(componentIds);**这一段给删掉了，
导致CDN数据直接获取的screen里面的，
应该是我代码的问题，谢谢了。
